spring:
  batch:
    job:
      names: SIMPLE_JOB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/batch
    username: root
    password: batch

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

excel:
  to:
    database:
      job:
        source:
          file:
            path: "excel/test.xlsx"